version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - './:/app/'
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - 'data-postgres:/var/lib/postgresql/data'

volumes:
  data-postgres:
    driver: local